# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.member_type:
        class: AppBundle\Form\MemberType
        arguments: ["%%avatar_directory%%"]

    app.session_idle:
        class: AppBundle\EventListener\SessionIdleListener
        arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }