# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.member_type:
        class: AppBundle\Form\MemberType
        arguments: ["%%avatar_directory%%"]

