#HOME
app_home:
    path: /
    defaults: { _controller: AppBundle:Default:index }
#JUDOKA
app_judoka_list:
    path: /members
    defaults: { _controller: AppBundle:Members:list }

app_judoka_add:
    path: /members/add
    defaults: { _controller: AppBundle:Members:add }

app_judoka_update:
    path: /members/update
    defaults: { _controller: AppBundle:Members:update }

app_judoka_detail:
    path: /members/detail
    defaults: { _controller: AppBundle:Members:detail }

#AJAX
app_judoka_ajax_weight:
    path: /members/weights
    defaults: { _controller: AppBundle:Members:weights }
    options:
        expose: true

#EVENT
app_event_list:
    path: /events
    defaults: { _controller: AppBundle:Events:list }

app_event_add:
    path: /events/add
    defaults: { _controller: AppBundle:Events:add }

app_event_update:
    path: /events/update
    defaults: { _controller: AppBundle:Events:update }

app_event_add_member:
    path: /events/add
    defaults: { _controller: AppBundle:Events:addMembers}