app_home:
    path:      /
    defaults: { _controller: AppBundle:Default:index }

app_judoka_list:
    path:      /members
    defaults: { _controller: AppBundle:Members:list }

app_judoka_add:
    path:      /members/add
    defaults: { _controller: AppBundle:Members:add }

app_judoka_update:
    path:      /members/update
    defaults: { _controller: AppBundle:Members:update }

app_event_list:
    path:      /events
    defaults: { _controller: AppBundle:Events:list }