services:

# Manager
    app.manager.member:
        class: AppBundle\Manager\MemberManager
        arguments: ["@doctrine.orm.entity_manager"]

    app.manager.measure:
        class: AppBundle\Manager\MeasureManager
        arguments: ["@doctrine.orm.entity_manager"]